# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Version Control Systems
email: rbriggs@ucsb.edu
description: >- # this means to ignore newlines until "baseurl:"
  This page was created to help other students understand an often overlooked, yet extremely crucial
  aspect of software design: version controls systems. Why do VCSs matter? In a collaborative setting, 
  it is extemely important to know the whos, whens and whys of a project for effiency and debugging purposes. 
  By allowing teams to look at snapshots of old projects, log changes, and even revert to old verions of code, 
  VCSs have become a necessity in all modern software settings. 


baseurl: /MQ-CS-Edu # the subpath of your site, e.g. /blog
url: "https://briggsrr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Coming soon...
github_username:  briggsrr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
